# Generated by Django 3.2.5 on 2021-09-27 18:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanco',
            name='date',
            field=models.DateField(default=datetime.date(2021, 9, 27)),
        ),
        migrations.AddField(
            model_name='balanco',
            name='despesa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.despesa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balanco',
            name='receita',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.receita'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='despesa',
            name='date',
            field=models.DateField(default=datetime.date(2021, 9, 27)),
        ),
        migrations.AddField(
            model_name='receita',
            name='date',
            field=models.DateField(default=datetime.date(2021, 9, 27)),
        ),
    ]
