# Generated by Django 3.2.5 on 2021-09-27 20:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210927_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balanco',
            name='despesa',
        ),
        migrations.RemoveField(
            model_name='balanco',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='balanco',
            name='receita',
        ),
        migrations.AddField(
            model_name='balanco',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balanco',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='receita',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
