# Generated by Django 3.2.5 on 2021-09-27 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210927_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='balanco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.balanco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receita',
            name='balanco',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.balanco'),
            preserve_default=False,
        ),
    ]
